### ISSUE TITLE
App Cannot Redirect to Loged in path

### ISSUE THREAD

**Issue by MikeMwambia-TrojanSystem** [seanmtracey/w3id-middleware#11]
My application seems to be stuck at after verification of the user id it keeps refreshing the url
It's stuck at this point....
![redirect](https://user-images.githubusercontent.com/5917824/42435940-e04ee818-838a-11e8-80a3-cfa856c81e78.png)

my server is a simple one that has 2 routes one protected the other public.
I am using blue mix and I have my application commissioned on [here](https://w3.innovate.ibm.com/tools/sso/w3id/saml/instance/edit.html?execution=e6s1) 
```
`var express = require("express");
var path = require("path");
var app = express();
var configFolder = '/configFolder/gitHubPlugin.env';
var result = require('dotenv').config({path:path.join(__dirname,configFolder)});
var bodyParser = require('body-parser')
var w3id = require('w3id-middleware');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.get('/', function (req, res) {
  console.log("Here");
  res.send("Hello");
});
app.use(w3id);
app.get('/authenticate', function (req, res) {
  console.log("Authenticated");
  res.send('Hello get');
});
var port = process.env.PORT || 3050
app.listen(port, function() {
    console.log("To view your app, open this link in your browser: http://localhost:" + port);
});`
```

The application as you can tell has two routes one public and the other private however it gets stuck at please wait point....
Any help is highly appreciated....?

**Comment by seanmtracey** [comment]
Do you have a public URL for your server? Or logs from your application on IBM Cloud?

**Comment by seanmtracey** [comment]
When I deploy your code myself, the login is successful, a valid session is created, and I can navigate between the `/` and `/authenticate routes` freely.
![image](https://user-images.githubusercontent.com/913687/43149517-7deb7fa2-8f5f-11e8-86ed-03f150928603.png)

There may be an error in your configuration when you registered the service with W3ID. Do you have those details available to you too?

**Comment by seanmtracey** [comment]
I've just noticed that I didn't document that your ACS URL in the W3ID registration must be `https://[your_domain_url]/__auth`. Try with that configuration and see if everything works.

**Comment by theEthAdams** [comment]
I will try and get back to you....Thanks.
