### ISSUE TITLE
IDP signature is not validated

### ISSUE THREAD

**Issue by in1723** [seanmtracey/w3id-middleware#6]
The POST request handler on  '/__auth' endpoint should validate the IDP signature of the assertion using the IDP public certificate.
Otherwise the application using this component will be vulnerable to forged IDP POST request with arbitrary credentials, allowing a malicious user to be "authenticated" as any application user.

https://github.com/seanmtracey/w3id-middleware/blob/e7fae0ebfd910753abee69e07a6336a51569daeb/index.js#L167

**Comment by seanmtracey** [comment]
Addressed with #7 (following Igor's advice), with further features/improvements discussed for implementation in the near future.
